#############################################################################
# Given a MAF file, its index generated by maf_index.py, and a bed file,
# this script will output al
#
# Gregg Thomas, April 2025
#############################################################################
"""
maf_fetch_exact_by_region.py

This script fetches alignment blocks from a MAF file that overlap regions
specified in a BED file and then trims those blocks so that only the exact
portion corresponding to the BED region (based on the reference coordinates)
is output. Each BED region is written to its own output file.

For the BED file:
  - Columns 1-3 are required: scaffold, start (0-based), end (non-inclusive)
  - If a 4th column is provided, it is used as the output file basename.
  - If not, the output file basename is constructed as "scaffold.counter" (e.g. scaff1.1, scaff1.2).

The MAF index file is assumed to have these tab-delimited fields:
    1. Reference scaffold
    2. Reference position (0-based)
    3. Alignment block sequence length
    4. Alignment block line length
    5. Number of sequences in the alignment block
    6. Start byte offset of the block in the MAF file
    7. End byte offset of the block in the MAF file

Usage:
    python3 maf_fetch_exact_by_region.py <maf_file> <index_file> <bed_file> [output_directory]

If [output_directory] is omitted, files are written to the current directory.
"""

#############################################################################

import sys
import os
import gzip

#############################################################################

def detectCompression(filename):
    """
    Detect the compression type for a given filename by examining its magic bytes.
    Returns "gz" for gzipped files or "none" if uncompressed.
    """
    compression_type = "none"
    magic_dict = {
        b"\x1f\x8b\x08": "gz",
        # Additional types (bz2, zip) could be added here if needed.
    }
    max_len = max(len(x) for x in magic_dict)
    with open(filename, "rb") as f:
        file_start = f.read(max_len)
    for magic_string in magic_dict:
        if file_start.startswith(magic_string):
            compression_type = magic_dict[magic_string]
            break
    return compression_type

#############################################################################

def parse_index(index_file):
    """
    Parse the index file and return a dictionary mapping scaffold names to a list of index entries.
    Each entry is a dictionary with:
        - ref_start: Reference start coordinate (0-based) of the block.
        - seq_length: Number of non-gap bases in the block on the reference.
        - offset_start: Starting byte offset of the block in the MAF file.
        - offset_end: Ending byte offset of the block in the MAF file.
    """
    index = {}
    with open(index_file, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            fields = line.split("\t")
            try:
                scaffold = fields[0]
                ref_start = int(fields[1])
                seq_length = int(fields[2])
                offset_start = int(fields[5])
                offset_end = int(fields[6])
            except (IndexError, ValueError):
                print(f"Skipping malformed index line: {line}", file=sys.stderr)
                continue
            entry = {
                "ref_start": ref_start,
                "seq_length": seq_length,
                "offset_start": offset_start,
                "offset_end": offset_end
            }
            index.setdefault(scaffold, []).append(entry)
    # Sort each scaffold's entries by reference start.
    for scaffold in index:
        index[scaffold].sort(key=lambda x: x["ref_start"])
    return index

#############################################################################

def parse_bed(bed_file):
    """
    Parse the BED file and return a list of region dictionaries.
    Each region contains:
        - scaffold: scaffold name.
        - start: region start (0-based).
        - end: region end (non-inclusive).
        - basename: if a 4th column exists, that value; otherwise, None.
    """
    regions = []
    with open(bed_file, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            fields = line.split()
            try:
                scaffold = fields[0]
                start = int(fields[1])
                end = int(fields[2])
            except (IndexError, ValueError):
                print(f"Skipping malformed BED line: {line}", file=sys.stderr)
                continue
            region = {"scaffold": scaffold, "start": start, "end": end}
            region["basename"] = fields[3] if len(fields) >= 4 else None
            regions.append(region)
    return regions

#############################################################################

def trim_maf_block(block_text, bed_start, bed_end):
    """
    Given a full MAF block text and BED coordinates (bed_start, bed_end),
    trim the block so that only the portion overlapping [bed_start, bed_end)
    on the reference is returned.

    Assumes the reference sequence is on the first "s" line (typically the second line
    of the block) with this format:
      s <src> <start> <size> <strand> <srcSize> <aligned_sequence>

    Returns the trimmed block text (string). If no overlap is found, returns None.
    """
    lines = block_text.splitlines()
    if len(lines) < 2:
        return None  # Not a valid block

    trimmed_lines = []
    # Copy header line if it starts with "a"; otherwise, insert a dummy header.
    if lines[0].startswith("a"):
        trimmed_lines.append(lines[0])
    else:
        trimmed_lines.append("a")
    
    ref_line_found = False
    ref_col_start = None
    ref_col_end = None
    new_ref_start = None
    new_ref_size = None

    for line in lines[1:]:
        if not line.startswith("s "):
            # Copy non-"s" lines (such as comments) unchanged.
            trimmed_lines.append(line)
            continue
        fields = line.split()
        # fields: ["s", src, start, size, strand, srcSize, sequence]
        if not ref_line_found:
            ref_line_found = True
            try:
                block_ref_start = int(fields[2])
                block_ref_size = int(fields[3])
            except ValueError:
                print("Error parsing reference coordinates in MAF block.", file=sys.stderr)
                return None
            ref_seq = fields[6]
            # Determine overlap between block and BED region.
            overlap_start = max(bed_start, block_ref_start)
            overlap_end = min(bed_end, block_ref_start + block_ref_size)
            if overlap_start >= overlap_end:
                return None  # No overlap.
            # Map overlap to alignment columns.
            current_ref = block_ref_start
            col_start = None
            col_end = None
            for i, char in enumerate(ref_seq):
                if current_ref == overlap_start and col_start is None:
                    col_start = i
                if char != '-':
                    current_ref += 1
                if current_ref == overlap_end:
                    col_end = i + 1  # include this column in the slice
                    break
            if col_start is None:
                return None
            if col_end is None:
                col_end = len(ref_seq)
            ref_col_start = col_start
            ref_col_end = col_end
            new_ref_start = overlap_start
            new_ref_size = sum(1 for c in ref_seq[ref_col_start:ref_col_end] if c != '-')
            # Update the reference line.
            new_fields = fields.copy()
            new_fields[2] = str(new_ref_start)
            new_fields[3] = str(new_ref_size)
            new_fields[6] = ref_seq[ref_col_start:ref_col_end]
            trimmed_lines.append(" ".join(new_fields))
        else:
            # For non-reference s-lines, trim sequence columns similarly.
            new_fields = fields.copy()
            new_fields[6] = fields[6][ref_col_start:ref_col_end]
            trimmed_lines.append(" ".join(new_fields))
    return "\n".join(trimmed_lines)

#############################################################################

def main():
    if len(sys.argv) < 4 or " -h" in sys.argv:
        sys.exit("Usage: python3 maf_fetch_exact_by_region.py <maf_file> <index_file> <bed_file> [output_directory]")
    
    maf_file = sys.argv[1]
    index_file = sys.argv[2]
    bed_file = sys.argv[3]
    out_dir = sys.argv[4] if len(sys.argv) > 4 else "."

    if not os.path.exists(out_dir):
        os.makedirs(out_dir)
    
    # Parse index and BED files.
    index = parse_index(index_file)
    regions = parse_bed(bed_file)

    maf_compression = detectCompression(maf_file)
    if maf_compression == "gz":
        opener = gzip.open
        open_mode = "rb"
    elif maf_compression == "none":
        opener = open
        open_mode = "rb"
    else:
        sys.exit(f"Unsupported compression type: {maf_compression}")
    
    maf_fp = opener(maf_file, open_mode)

    # Create a dictionary to hold region counters per scaffold for regions lacking a 4th column.
    region_counter = {}

    for region in regions:
        scaffold = region["scaffold"]
        bed_start = region["start"]
        bed_end = region["end"]

        # Determine basename for output file.
        if region["basename"]:
            out_basename = region["basename"]
        else:
            count = region_counter.get(scaffold, 0) + 1
            region_counter[scaffold] = count
            out_basename = f"{scaffold}.{count}"
        output_filename = os.path.join(out_dir, out_basename + ".maf")
        
        # Open individual output file for this region.
        with open(output_filename, "w", encoding="utf-8") as out_stream:
            print(f">>> Region {scaffold}:{bed_start}-{bed_end}");
            if scaffold not in index:
                print(f"No index entries for scaffold {scaffold}");
                continue
            found_any = False
            for entry in index[scaffold]:
                block_ref_start = entry["ref_start"]
                block_ref_end = block_ref_start + entry["seq_length"]
                # Check if the block overlaps the BED region.
                if bed_start < block_ref_end and bed_end > block_ref_start:
                    try:
                        maf_fp.seek(entry["offset_start"])
                        block_bytes = maf_fp.read(entry["offset_end"] - entry["offset_start"])
                        block_text = block_bytes.decode("utf-8", errors="replace")
                    except Exception as e:
                        print(f"Error fetching block: {e}", file=sys.stderr)
                        continue
                    trimmed = trim_maf_block(block_text, bed_start, bed_end)
                    if trimmed:
                        out_stream.write(trimmed)
                        out_stream.write("\n")
                        found_any = True
            if not found_any:
                print(f"No overlapping block found for {scaffold}.\n")
    
    maf_fp.close()

#############################################################################

if __name__ == "__main__":
    main();

#############################################################################
