#############################################################################
# Given a MAF file, its index generated by maf_index.py, and a bed file,
# this script will output al
#
# Gregg Thomas, April 2025
#############################################################################

"""
maf_fetch_exact_by_region_parallel.py

This script fetches alignment blocks from a MAF file that overlap regions
specified in a BED file, trims those blocks so that only the exact portion overlapping 
the BED region is output, and writes each region’s output to its own file.
Processing is parallelized on a per-region basis using ProcessPoolExecutor.

For the BED file:
  - Columns 1–3 are required: scaffold, start (0-based), end (non-inclusive).
  - If a 4th column is provided, it is used as the output file basename.
  - If missing, a unique basename is generated as "scaffold.counter" (e.g. scaff1.1, scaff1.2, etc.)

The MAF index file is assumed to have the following tab‑delimited fields:
    1. Reference scaffold
    2. Reference position (0-based)
    3. Alignment block sequence length
    4. Alignment block line length
    5. Number of sequences in the alignment block
    6. Start byte offset of the block in the MAF file
    7. End byte offset of the block in the MAF file

Usage:
    python maf_fetch_exact_by_region_parallel.py <maf_file> <index_file> <bed_file> [output_directory] [max_workers (default=1)]

If [output_directory] is omitted, files are written to the current directory.
If [max_workers] is omitted, it defaults to 1.
"""

import sys
import os
import gzip
from concurrent.futures import ProcessPoolExecutor

#############################################################################

def detectCompression(filename):
    """
    Detects whether the file is gzipped (returns "gz") or not (returns "none").
    """
    compression_type = "none"
    magic_dict = {
        b"\x1f\x8b\x08": "gz",
        # (Other compression types could be added if needed.)
    }
    max_len = max(len(x) for x in magic_dict)
    with open(filename, "rb") as f:
        file_start = f.read(max_len)
    for magic_string in magic_dict:
        if file_start.startswith(magic_string):
            compression_type = magic_dict[magic_string]
            break
    return compression_type

#############################################################################

def parseIndex(index_file):
    """
    Parses the index file into a dictionary keyed by scaffold.
    Each index entry (a dict) contains:
        - ref_start: reference start coordinate (0-based)
        - seq_length: alignment block sequence length (number of bases on the reference)
        - offset_start: byte offset start in the MAF file
        - offset_end: byte offset end in the MAF file
    """
    index = {}
    with open(index_file, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            fields = line.split("\t")
            try:
                scaffold = fields[0]
                ref_start = int(fields[1])
                seq_length = int(fields[2])
                offset_start = int(fields[5])
                offset_end = int(fields[6])
            except (IndexError, ValueError):
                print(f"Skipping malformed index line: {line}", file=sys.stderr)
                continue
            entry = {
                "ref_start": ref_start,
                "seq_length": seq_length,
                "offset_start": offset_start,
                "offset_end": offset_end
            }
            index.setdefault(scaffold, []).append(entry)
    for scaffold in index:
        index[scaffold].sort(key=lambda x: x["ref_start"])
    return index

#############################################################################

def parseBed(bed_file):
    """
    Parses the BED file into a list of region dictionaries.
    Each region has keys:
        - scaffold (chromosome)
        - start (integer, 0-based)
        - end (integer, non-inclusive)
        - basename (from column 4, if present; otherwise None)
    """
    regions = []
    with open(bed_file, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            fields = line.split()
            try:
                scaffold = fields[0]
                start = int(fields[1])
                end = int(fields[2])
            except (IndexError, ValueError):
                print(f"Skipping malformed BED line: {line}", file=sys.stderr)
                continue
            region = {"scaffold": scaffold, "start": start, "end": end, "id": None}
            if len(fields) >= 4:
                region["id"] = fields[3]
            regions.append(region)
    return regions

#############################################################################

def trimMafBlock(block_text, bed_start, bed_end):
    """
    Trims a MAF block to exactly the portion overlapping [bed_start, bed_end)
    on the reference sequence. Assumes the reference sequence is given in the
    first "s" line after the header.

    The MAF "s" line format:
        s <src> <start> <size> <strand> <srcSize> <aligned_sequence>

    Returns the trimmed block as a string, or None if no overlap occurs.
    """
    lines = block_text.splitlines()
    if len(lines) < 2:
        return None  # Invalid block
    trimmed_lines = []
    if lines[0].startswith("a"):
        trimmed_lines.append(lines[0])
    else:
        trimmed_lines.append("a")
    
    ref_line_found = False
    ref_col_start = None
    ref_col_end = None
    new_ref_start = None
    new_ref_size = None
    for line in lines[1:]:
        if not line.startswith("s "):
            trimmed_lines.append(line)
            continue
        fields = line.split()
        if not ref_line_found:
            ref_line_found = True
            try:
                block_ref_start = int(fields[2])
                block_ref_size = int(fields[3])
            except ValueError:
                sys.exit("Error parsing reference coordinates in MAF block.")
            ref_seq = fields[6]
            # Determine overlap with the block.
            overlap_start = max(bed_start, block_ref_start)
            overlap_end = min(bed_end, block_ref_start + block_ref_size)
            if overlap_start >= overlap_end:
                return None  # No overlap.
            # Map the overlap to alignment columns.
            current_ref = block_ref_start
            col_start = None
            col_end = None
            for i, char in enumerate(ref_seq):
                if current_ref == overlap_start and col_start is None:
                    col_start = i
                if char != '-':
                    current_ref += 1
                if current_ref == overlap_end:
                    col_end = i + 1  # include this column
                    break
            if col_start is None:
                return None
            if col_end is None:
                col_end = len(ref_seq)
            ref_col_start = col_start
            ref_col_end = col_end
            new_ref_start = overlap_start
            new_ref_size = sum(1 for c in ref_seq[ref_col_start:ref_col_end] if c != '-')
            new_fields = fields.copy()
            new_fields[2] = str(new_ref_start)
            new_fields[3] = str(new_ref_size)
            new_fields[6] = ref_seq[ref_col_start:ref_col_end]
            trimmed_lines.append(" ".join(new_fields))
        else:
            new_fields = fields.copy()
            new_fields[6] = fields[6][ref_col_start:ref_col_end]
            trimmed_lines.append(" ".join(new_fields))
    return "\n".join(trimmed_lines)

#############################################################################

def processRegion(region, maf_file, maf_compression, index, out_dir):
    """
    Worker function to process a single BED region:
      - Opens the MAF file independently.
      - Finds overlapping blocks in the index for region["scaffold"].
      - For each overlapping block, fetches and trims the block to the 
        exact [region["start"], region["end"]) interval on the reference.
      - Writes the trimmed blocks to an output file, using region["output_basename"] as filename.
    Returns a message summarizing the work.
    """
    scaffold = region["scaffold"]
    bed_start = region["start"]
    bed_end = region["end"]
    out_basename = region["output_basename"]
    output_filename = os.path.join(out_dir, out_basename + ".maf")

    # Open the MAF file using the appropriate opener.
    if maf_compression == "gz":
        opener = gzip.open
        open_mode = "rb"
    else:
        opener = open
        open_mode = "rb"

    try:
        maf_fp = opener(maf_file, open_mode)
    except Exception as e:
        sys.exit(f"Region {scaffold}:{bed_start}-{bed_end}: Error opening MAF file: {e}");

    blocks_written = 0;

    with open(output_filename, "w", encoding="utf-8") as out_stream:
        print(f">>> Region {scaffold}:{bed_start}-{bed_end}")
        if scaffold not in index:
            maf_fp.close()
            return f"{output_filename}: No index entries for scaffold {scaffold}"
        for entry in index[scaffold]:
            block_ref_start = entry["ref_start"]
            block_ref_end = block_ref_start + entry["seq_length"]
            if bed_start < block_ref_end and bed_end > block_ref_start:
                try:
                    maf_fp.seek(entry["offset_start"])
                    block_bytes = maf_fp.read(entry["offset_end"] - entry["offset_start"])
                    block_text = block_bytes.decode("utf-8", errors="replace")
                except Exception as e:
                    sys.exit(f"Error fetching block: {e}\n");
                trimmed = trimMafBlock(block_text, bed_start, bed_end)
                if trimmed:
                    out_stream.write(trimmed)
                    out_stream.write("\n")
                    blocks_written += 1
        if not blocks_written:
            print(f"{scaffold}:{bed_start}-{bed_end} No overlapping blocks found.\n");
    maf_fp.close()
    return f"{output_filename}: Wrote {blocks_written} blocks for region {scaffold}:{bed_start}-{bed_end}";

#############################################################################

def main():
    if len(sys.argv) < 4 or " -h" in sys.argv or "--help" in sys.argv:
        print(__doc__);
        sys.exit("Usage: python maf_fetch_exact_by_region_parallel.py <maf_file> <index_file> <bed_file> [output_directory] [max_workers]");
    # Print help message and exit if not enough arguments are provided.

    maf_file = sys.argv[1]
    index_file = sys.argv[2]
    bed_file = sys.argv[3]
    out_dir = sys.argv[4] if len(sys.argv) > 4 else "."
    max_workers = int(sys.argv[5]) if len(sys.argv) > 5 else 1
    # Get inputs from command line

    if not os.path.exists(out_dir):
        os.makedirs(out_dir)
    # Create output directory if it doesn't exist.

    # Parse index and BED files.
    index = parseIndex(index_file);
    regions = parseBed(bed_file);

    # Pre-assign output basenames for regions.
    # For regions missing a 4th column (basename), assign a unique counter per scaffold.
    region_counter = {}
    for region in regions:
        scaffold = region["scaffold"]
        if region["id"]:
            region["output_basename"] = region["id"]
        else:
            count = region_counter.get(scaffold, 0) + 1
            region_counter[scaffold] = count
            region["output_basename"] = f"{scaffold}.{count}"

    maf_compression = detectCompression(maf_file)
    if maf_compression not in ("gz", "none"):
        sys.exit(f"Unsupported compression type: {maf_compression}")

    # Process each region in parallel.
    results = []
    with ProcessPoolExecutor(max_workers=max_workers) as executor:
        futures = []
        for region in regions:
            futures.append(executor.submit(processRegion, region, maf_file, maf_compression, index, out_dir))
        for future in futures:
            result = future.result()
            print(result)
            results.append(result)

if __name__ == "__main__":
    main()
