#############################################################################
# Given a MAF file and its index generated by maf_index.py, this script will
# split the MAF file into separate files for each chromosome.
#
# Gregg Thomas, April 2025
#############################################################################

import sys
import os
import gzip
from concurrent.futures import ProcessPoolExecutor

#############################################################################

def detectCompression(filename):
    """
    Detect the compression type for a given filename by examining its magic bytes.
    Returns "gz" for gzipped files, "bz2" for bzip2, "zip" for zip archives, or "none".
    """
    compression_type = "none"
    magic_dict = {
        b"\x1f\x8b\x08": "gz",
        b"\x42\x5a\x68": "bz2",
        b"\x50\x4b\x03\x04": "zip"
    }
    max_len = max(len(x) for x in magic_dict)
    with open(filename, "rb") as f:
        file_start = f.read(max_len)
    for magic_string in magic_dict:
        if file_start.startswith(magic_string):
            compression_type = magic_dict[magic_string]
            break
    return compression_type

#############################################################################

def make_output_filename(maf_file, scaffold):
    """
    Build the output file name using the input MAF file's base name and the scaffold name.
    For example, given "turtles.Dcoriacea.nodupes.maf.gz" and scaffold "scaff-1",
    it returns "turtles.Dcoriacea.nodupes.scaff-1.maf".
    """
    base = os.path.basename(maf_file)
    # Remove .gz if present
    if base.endswith(".gz"):
        base = base[:-3]
    # Remove .maf if present
    if base.endswith(".maf"):
        base = base[:-4]
    return f"{base}.{scaffold}.maf"

#############################################################################

def process_scaffold(scaffold, blocks, maf_file, maf_compression, out_dir):
    """
    Process all blocks for a given scaffold:
      - Open the MAF file (using a separate file handle)
      - Fetch all alignment blocks defined by the list of (start, end) tuples
      - Write the blocks to an output file specific to the scaffold.
    """

    print(f"Processing scaffold {scaffold} with {len(blocks)} blocks... ");

    # Choose the appropriate opener and open mode (binary mode for random access)
    if maf_compression == "gz":
        opener = gzip.open
        open_mode = "rb"
    elif maf_compression == "none":
        opener = open
        open_mode = "rb"
    else:
        raise ValueError(f"Unsupported compression type: {maf_compression}")
    
    out_file = os.path.join(out_dir, make_output_filename(maf_file, scaffold))
    with open(out_file, "w", encoding="utf-8") as outf:
        with opener(maf_file, open_mode) as maf_fp:
            for start, end in blocks:
                maf_fp.seek(start)
                block_bytes = maf_fp.read(end - start)
                block_text = block_bytes.decode("utf-8", errors="replace")
                outf.write(block_text)
                outf.write("\n")  # Optionally separate blocks with a newline

    return f"Wrote {len(blocks)} blocks from scaffold {scaffold} to {out_file}"

#############################################################################

def main():
    if len(sys.argv) < 3:
        sys.exit("Usage: python3 split_maf_by_scaffold_parallel.py <maf_file> <index_file> [output_directory] [num_procs (default=1)]")
    
    maf_file = sys.argv[1]
    index_file = sys.argv[2]
    out_dir = sys.argv[3] if len(sys.argv) >= 4 else ".";
    num_procs = int(sys.argv[4]) if len(sys.argv) >= 5 else 1;

    if not os.path.exists(out_dir):
        os.makedirs(out_dir)
    
    # Detect the compression of the MAF file. We support gzipped or uncompressed files.
    maf_compression = detectCompression(maf_file)
    if maf_compression not in ("gz", "none"):
        sys.exit(f"Unsupported compression type for splitting: {maf_compression}")

    # Read the index file and ignore comment/empty lines.
    with open(index_file, "r") as idx_fp:
        index_lines = [line.strip() for line in idx_fp if line.strip() and not line.startswith("#")]

    # Build the scaffold_blocks dictionary.
    # Each key is a scaffold name; the value is a list of (start, end) tuples.
    scaffold_blocks = {}
    for line in index_lines:
        fields = line.split("\t")
        try:
            scaffold = fields[0]
            start = int(fields[5])
            end = int(fields[6])
        except (IndexError, ValueError):
            print(f"Skipping malformed index line: {line}")
            continue
        scaffold_blocks.setdefault(scaffold, []).append((start, end))
    
    # Ensure that the blocks for each scaffold are in order.
    for scaffold in scaffold_blocks:
        scaffold_blocks[scaffold].sort(key=lambda pair: pair[0])

    # Process each scaffold in parallel. Each worker will process one scaffold.
    with ProcessPoolExecutor(max_workers=num_procs) as executor:
        futures = []
        for scaffold, blocks in scaffold_blocks.items():
            futures.append(
                executor.submit(process_scaffold, scaffold, blocks, maf_file, maf_compression, out_dir)
            )
        for future in futures:
            print(future.result())

#############################################################################

if __name__ == "__main__":
    main()

#############################################################################