#############################################################################
# Given a MAF file, its index generated by maf_index.py, and a bed file,
# this script will output the alignment blocks from the MAF file that overlap
# the regions specified in the bed file. The output will be trimmed to only
# include the exact portion of the alignment block that overlaps the bed region.
#
# Gregg Thomas, April 2025
#############################################################################

"""
maf_fetch.py

This script fetches alignment blocks from a MAF (Multiple Alignment Format) file
that overlap regions specified in a BED file. It works in two modes:

    Block mode:
        - Uses a block-level index
        - Extracts blocks overlapping each [start, end) BED interval
        - Trims blocks to exactly match the specified region
        - Output files are named by region ID or scaffold.counter (e.g., chr1.1.maf)

    Scaffold mode:  
        - Uses a scaffold-level index
        - Treats the BED file as a list of scaffold names (only column 1 is required)
        - Extracts all alignment blocks for each scaffold from the MAF
        - Output files are named by scaffold (e.g., chr1.maf, chrZ.maf)

Parallelization:
    - Block mode is parallelized by region
    - Scaffold mode is parallelized by scaffold
    - The number of processes can be controlled with --processes

Required input:
    - A MAF file (.maf or .maf.gz)
    - A MAF index file (from maf_index.py)
    - A BED file

Optional arguments:
    --outdir, -o         Output directory (default: current directory)
    --processes, -p      Number of parallel processes (default: 1)
    --mode, -m           Mode: 'block' or 'scaffold' (default: 'block')

Compression:
    - Gzipped MAF files (.maf.gz) are supported, provided the index is built
    from the compressed file using gzip.open()

Usage:
    python maf_fetch.py <maf_file> <index_file> <bed_file> [--outdir DIR] [--processes N] [--mode block|scaffold]

Examples:
    Block mode with 4 threads:
        python maf_fetch.py alignment.maf.gz index.idx regions.bed --processes 4

    Scaffold mode with default output:
        python maf_fetch.py alignment.maf.gz index.idx scaffolds.bed --mode scaffold
"""

import sys
import os
import argparse
import gzip
from concurrent.futures import ProcessPoolExecutor

import lib.common as COMMON

#############################################################################

def optParse():
    parser = argparse.ArgumentParser(
    description="""
        Extract alignment blocks from a MAF file based on a BED file of regions or scaffolds.

        Supports two modes:
        - block    : Extracts and trims blocks to exactly match BED intervals.
        - scaffold : Extracts complete alignment blocks for listed scaffolds, untrimmed.

        Parallel execution is supported for both modes; output is written per region or scaffold.
        """,
        formatter_class=argparse.RawDescriptionHelpFormatter  # Preserves line breaks
    )
    
    parser.add_argument("maf_file", help="Input MAF file (.maf or .maf.gz)")
    parser.add_argument("index_file", help="Index file (block-level .idx or scaffold-level .idx)")
    parser.add_argument("bed_file", help="BED file with regions or scaffold names to extract")

    parser.add_argument(
        "--basename", "-b",
        choices=["id", "coords", "count"],
        default="coords",
        help="Basename strategy: 'id' (BED 4th col if present), 'coords' (scaffold-start-end), or 'count' (numbered per scaffold)"
    )

    parser.add_argument(
        "--output", "-o", default=".",
        help="Output directory (default: current directory); "
        "if --single-output is used, this should instead be a filename and will default to maf-fetch.maf in the current directory."
    )
    
    parser.add_argument(
        "--fasta", "-f", action="store_true", default=False,
        help="Output region(s) in FASTA format instead of MAF."
    )

    parser.add_argument(
        "--processes", "-p", type=int, default=1,
        help="Number of parallel processes to use (default: 1)"
    )
    parser.add_argument(
        "--mode", "-m", choices=["block", "scaffold"], default="block",
        help="Mode: 'block' to trim by regions, 'scaffold' to extract whole scaffolds (default: block)"
    )

    parser.add_argument(
        "--single-output", "-s", action="store_true", default=False,
        help="If set, output all blocks to a single MAF file specified by --output (default: maf-fetch.maf)."
    )

    return parser.parse_args()

#############################################################################

def parseIndex(index_file, mode="block"):
    """
    Parses either a block-level or region-level index file.

    For block mode:
        Returns: { scaffold: [ { ref_start, seq_length, offset_start, offset_end }, ... ] }

    For scaffold mode:
        Returns: { scaffold: (byte_start, byte_end) } — one entry per scaffold
    """
    index = {}

    with open(index_file, "r") as f:
        for line in f:
            if line.startswith("#") or not line.strip():
                continue
            fields = line.strip().split("\t")

            if mode == "block":
                if len(fields) < 7:
                    print(f"[WARN] Skipping malformed index line: {line.strip()}", file=sys.stderr)
                    continue
                scaffold = fields[0]
                try:
                    ref_start = int(fields[1])
                    seq_length = int(fields[2])
                    offset_start = int(fields[5])
                    offset_end = int(fields[6])
                except ValueError:
                    continue
                entry = {
                    "ref_start": ref_start,
                    "seq_length": seq_length,
                    "offset_start": offset_start,
                    "offset_end": offset_end
                }
                index.setdefault(scaffold, []).append(entry)

            elif mode == "scaffold":
                if len(fields) != 3:
                    print(f"[WARN] Skipping malformed index line: {line.strip()}", file=sys.stderr)
                    continue
                scaffold = fields[0]
                try:
                    offset_start = int(fields[1])
                    offset_end = int(fields[2])
                except ValueError:
                    continue
                index[scaffold] = (offset_start, offset_end)

    # Sort block entries per scaffold
    if mode == "block":
        for scaffold in index:
            index[scaffold].sort(key=lambda x: x["ref_start"])

    return index

#############################################################################

def parseBed(bed_file, mode="block"):
    """
    Parses the BED file into a list of region dictionaries.

    In "block" mode: expects at least 3 columns (scaffold, start, end)
    Each region has keys:
        - scaffold (chromosome)
        - start (integer, 0-based)
        - end (integer, non-inclusive)
        - basename (from column 4, if present; otherwise None)

    In "scaffold" mode: accepts 1+ columns; only uses first column (scaffold)
    """
    regions = []
    with open(bed_file, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            fields = line.split()
            if mode == "scaffold":
                scaffold = fields[0]
                region = {"scaffold": scaffold, "start": 0, "end": 0, "id": fields[3] if len(fields) >= 4 else None}
                regions.append(region)
            else:
                # block mode: require at least 3 columns (scaffold/start/end)
                try:
                    scaffold = fields[0]
                    start = int(fields[1])
                    end = int(fields[2])
                    region = {"scaffold": scaffold, "start": start, "end": end, "id": fields[3] if len(fields) >= 4 else None}
                    regions.append(region)
                except (IndexError, ValueError):
                    print(f"Skipping malformed BED line: {line}", file=sys.stderr)
                    continue
    return regions

#############################################################################

def getMAFHeader(maf_file, maf_compression):
    """Return header lines (starting with ##) from the MAF file, skipping blank lines."""
    headers = []
    if maf_compression == "gz":
        opener = gzip.open
        mode = "rt"
    else:
        opener = open
        mode = "rt"
    with opener(maf_file, mode) as fp:
        for line in fp:
            line = line.strip()
            if not line:  # Skip blank lines
                continue
            if line.startswith("##"):
                headers.append(line)
            else:
                break
    # print(f"Found {len(headers)} header lines in MAF file.")
    # print(f"Header lines:\n{headers}")
    # sys.exit();
    return "\n".join(headers) + "\n"

#############################################################################

def mafBlockToFasta(block_text, region=None):
    """
    Converts a (trimmed) MAF block to multi-FASTA format. 
    Optionally, include region/scaffold in headers.
    """
    fasta_lines = []
    lines = block_text.strip().splitlines()
    
    # Compose region description
    header_fields = []
    if region:
        if "scaffold" in region and "start" in region and "end" in region:
            header_fields.append(f"{region['scaffold']}:{region['start']}-{region['end']}")
        # Add id if present
        if "id" in region and region["id"]:
            header_fields.append(f"id:{region['id']}")

        # (You could customize more info if you like)
    description = " ".join(header_fields).strip()
    
    for line in lines:
        if line.startswith("s "):
            fields = line.split()
            src = fields[1]
            seq = fields[6]
            header = f">{src}"
            if description:
                header += f" {description}"
            fasta_lines.append(header)
            fasta_lines.append(seq)
    return "\n".join(fasta_lines)

#############################################################################

def trimMafBlock(block_text, bed_start, bed_end):
    """
    Trims a MAF block to exactly the portion overlapping [bed_start, bed_end)
    on the reference sequence. Assumes the reference sequence is given in the
    first "s" line after the header.

    The MAF "s" line format:
        s <src> <start> <size> <strand> <srcSize> <aligned_sequence>

    Returns the trimmed block as a string, or None if no overlap occurs.
    """
    lines = block_text.splitlines()
    if len(lines) < 2:
        return None  # Invalid block
    trimmed_lines = []
    if lines[0].startswith("a"):
        trimmed_lines.append(lines[0])
    else:
        trimmed_lines.append("a")
    
    ref_line_found = False
    ref_col_start = None
    ref_col_end = None
    new_ref_start = None
    new_ref_size = None
    for line in lines[1:]:
        if not line.startswith("s "):
            trimmed_lines.append(line)
            continue
        fields = line.split()
        if not ref_line_found:
            ref_line_found = True
            try:
                block_ref_start = int(fields[2])
                block_ref_size = int(fields[3])
            except ValueError:
                sys.exit("[ERROR] Error parsing reference coordinates in MAF block.")
            ref_seq = fields[6]
            # Determine overlap with the block.
            overlap_start = max(bed_start, block_ref_start)
            overlap_end = min(bed_end, block_ref_start + block_ref_size)
            if overlap_start >= overlap_end:
                return None  # No overlap.
            
            # FIXED: Map the overlap to alignment columns correctly
            current_ref = block_ref_start
            col_start = None
            col_end = None

            for i, char in enumerate(ref_seq):
                if char != '-':
                    # This is a real reference position
                    if current_ref >= overlap_start and col_start is None:
                        col_start = i
                    current_ref += 1
                    if current_ref >= overlap_end:  # Check AFTER incrementing
                        col_end = i + 1  # Include current position
                        break
                elif col_start is not None and col_end is None:
                    # We're in our target region and this is a gap - we'll include it
                    pass

            if col_start is None:
                return None
            if col_end is None:
                col_end = len(ref_seq)

            if col_start is not None:
                extracted_ref_bases = sum(1 for c in ref_seq[col_start:col_end] if c != '-')
                expected_bases = overlap_end - overlap_start
                if extracted_ref_bases != expected_bases:
                        print(f"[WARN] Expected {expected_bases} bases but extracted {extracted_ref_bases} for region {overlap_start}-{overlap_end}")   

            ref_col_start = col_start
            ref_col_end = col_end
            new_ref_start = overlap_start
            new_ref_size = sum(1 for c in ref_seq[ref_col_start:ref_col_end] if c != '-')
            new_fields = fields.copy()
            new_fields[2] = str(new_ref_start)
            new_fields[3] = str(new_ref_size)
            new_fields[6] = ref_seq[ref_col_start:ref_col_end]
            trimmed_lines.append(" ".join(new_fields))
        else:
            new_fields = fields.copy()
            new_fields[6] = fields[6][ref_col_start:ref_col_end]
            trimmed_lines.append(" ".join(new_fields))

    #print(f"DEBUG: bed_interval=[{bed_start},{bed_end}), block_ref=[{block_ref_start},{block_ref_start + block_ref_size}), extracted_cols=[{ref_col_start}:{ref_col_end}], ref_seq_sample='{ref_seq[ref_col_start:ref_col_end] if ref_col_start is not None else 'None'}'", file=sys.stderr)

    return "\n".join(trimmed_lines)

#############################################################################

def fetchByRegion(region, header, maf_file, maf_compression, index, output, single_output=False, as_fasta=False):
    """
    Worker function to process a single BED region:
        - Opens the MAF file independently.
        - Finds overlapping blocks in the index for region["scaffold"].
        - For each overlapping block, fetches and trims the block to the 
        exact [region["start"], region["end"]) interval on the reference.
        - Writes the trimmed blocks to an output file, using region["output_basename"] as filename.
    Returns a message summarizing the work.
    """

    scaffold = region["scaffold"]
    bed_start = region["start"]
    bed_end = region["end"]
    out_basename = region["output_basename"]

    # if bed_start not in ["9547874", 9547874]:
    #     return

    if not single_output:
        output_filename = os.path.join(output, out_basename + ".maf")
        out_stream = open(output_filename, "w", encoding="utf-8")
    else:
        current_blocks = []

    # Open the MAF file using the appropriate opener.
    if maf_compression == "gz":
        opener = gzip.open;
    else:
        opener = open;

    try:
        maf_fp = opener(maf_file, "rb")
    except Exception as e:
        if not single_output:
            out_stream.close()
        sys.exit(f"[ERROR] Region {scaffold}:{bed_start}-{bed_end}: Error opening MAF file: {e}");

    blocks_written = 0;

    print(f">>> Region {scaffold}:{bed_start}-{bed_end}")
    if scaffold not in index:
        maf_fp.close()
        if not single_output:
            out_stream.close()
        return f"{output_filename}: No index entries for scaffold {scaffold}"

    for entry in index[scaffold]:
        block_ref_start = entry["ref_start"]
        block_ref_end = block_ref_start + entry["seq_length"]
        if bed_start < block_ref_end and bed_end > block_ref_start:
            try:
                maf_fp.seek(entry["offset_start"])
                block_bytes = maf_fp.read(entry["offset_end"] - entry["offset_start"])
                block_text = block_bytes.decode("utf-8", errors="replace")
            except Exception as e:
                maf_fp.close()
                if not single_output:
                    out_stream.close()
                sys.exit(f"[ERROR] Error fetching block: {e}\n");
            
            # print(block_text)
            # os._exit(1)

            trimmed = trimMafBlock(block_text, bed_start, bed_end)
            if not single_output:
                if blocks_written == 0 and not as_fasta:
                    out_stream.write(header)
                if as_fasta:
                    # Output as fasta
                    out_stream.write(mafBlockToFasta(trimmed, region) + "\n")
                else:
                    out_stream.write(trimmed + "\n")
            else:
                if as_fasta:
                    current_blocks.append(mafBlockToFasta(trimmed, region) + "\n")
                else:
                    current_blocks.append(trimmed + "\n")
                blocks_written += 1

    maf_fp.close()

    if not blocks_written:
        print(f"{scaffold}:{bed_start}-{bed_end} No overlapping blocks found.\n");

    if not single_output:
        out_stream.close()
        return f"{output_filename}: Wrote {blocks_written} blocks for region {scaffold}:{bed_start}-{bed_end}";
    else:
        return current_blocks;

#############################################################################

def fetchByScaffold(scaffold, start_end, maf_file, maf_header, maf_compression, out_dir):
    """
    Worker function to extract one scaffold from the MAF file.
    start_end is a tuple (start_byte, end_byte).
    """
    start, end = start_end
    output_path = os.path.join(out_dir, f"{scaffold}.maf")

    # Open MAF file appropriately
    opener = gzip.open if maf_compression == "gz" else open

    try:
        with opener(maf_file, "rb") as mfp, open(output_path, "wb") as outfp:
            print(f">>> Scaffold {scaffold}");
            mfp.seek(start)
            data = mfp.read(end - start)
            outfp.write(maf_header.encode("utf-8"))
            outfp.write(data)
    except Exception as e:
        return f"[ERROR] {scaffold}: {e}"
    
    return f"{output_path}: Wrote {scaffold}";


#############################################################################

def main():
    # if len(sys.argv) < 4 or " -h" in sys.argv or "--help" in sys.argv:
    #     print(__doc__);
    #     sys.exit("Usage: python maf_fetch.py <maf_file> <index_file> <bed_file> [output_directory] [max_processes] [mode=block|scaffold]");
    # Print help message and exit if not enough arguments are provided.

    args = optParse()

    maf_file = args.maf_file
    index_file = args.index_file
    bed_file = args.bed_file
    output = args.output
    single_output = args.single_output
    max_processes = args.processes
    run_mode = args.mode
    # Get inputs from command line

    if run_mode not in ("block", "scaffold"):
        sys.exit(f"[ERROR] Invalid mode: '{run_mode}'. Must be 'block' or 'scaffold'.")

    maf_compression = COMMON.detectCompression(maf_file);
    if not single_output:
        os.makedirs(output, exist_ok=True);
    # Create output directory if it doesn't exist

    print(f"Parsing index file.... {index_file}");
    index = parseIndex(index_file, run_mode);

    print(f"Parsing BED file...... {bed_file}");
    regions = parseBed(bed_file, run_mode);

    print(f"Getting MAF header.... {maf_file}");
    maf_header = getMAFHeader(maf_file, maf_compression);

    ##############################
    # SCAFFOLD MODE
    ##############################

    if run_mode == "scaffold":
        if single_output:
            sys.exit("[ERROR] --single-output cannot be used in scaffold mode.");

        if args.fasta:
            sys.exit("[ERROR] FASTA output not supported in scaffold mode.")

        print(f"[INFO] Running in SCAFFOLD mode with BED + region index");
        
        # Parse the BED file to get a set of scaffolds to extract
        scaffold_set = set(region["scaffold"] for region in regions);
        print(f"[INFO] Extracting {len(scaffold_set)} scaffolds from scaffold index: {scaffold_set}");

        # Extract from MAF using the region index for matching scaffolds
        with ProcessPoolExecutor(max_workers=max_processes) as executor:
            futures = []
            for scaffold in scaffold_set:
                if scaffold not in index:
                    sys.exit(f"[ERROR] Scaffold '{scaffold}' not found in index.")
                start, end = index[scaffold]
                futures.append(executor.submit(
                    fetchByScaffold,
                    scaffold,
                    (start, end),
                    maf_file,
                    maf_header,
                    maf_compression,
                    output
                ))
            for future in futures:
                result = future.result()
                print(result)
        return;  # Done with scaffold mode

    ##############################
    # BLOCK MODE (default)
    ##############################

    print(f"[INFO] Running in BLOCK mode");

    if args.single_output:
        # NEW: Single output mode
        if args.output == "." or os.path.isdir(args.output):
            output_file = "maf-fetch.maf"
        else:
            if os.path.isdir(args.output):
                sys.exit("[ERROR] --single-output cannot be used with --outdir. Use current directory only.");
            output_file = args.output
        print(f"[INFO] Using single output file: {output_file}")

    # Pre-assign output basenames for regions.
    # For regions missing a 4th column (basename), assign a unique counter per scaffold.
    region_counter = {}
    for region in regions:
        scaffold = region["scaffold"]
        start = region["start"]
        end = region["end"]
        basename_mode = args.basename

        if basename_mode == "id":
            if region.get("id"):
                region["output_basename"] = region["id"]
            else:
                sys.exit(f"[ERROR] Basename mode set to 'id', but '{region}' lacks an ID (4th column).");
        elif basename_mode == "count":
            count = region_counter.get(scaffold, 0) + 1
            region_counter[scaffold] = count
            region["output_basename"] = f"{scaffold}.{count}"
        else: # basename_mode == "coords":
            region["output_basename"] = f"{scaffold}-{start}-{end}"

    # Process each region in parallel.
    results = [];
    with ProcessPoolExecutor(max_workers=max_processes) as executor:
        futures = [];
        for region in regions:
            futures.append(executor.submit(
                fetchByRegion,
                region,
                maf_header,
                maf_file,
                maf_compression,
                index,
                output,
                single_output,
                args.fasta
            ));
        for future in futures:
            result = future.result();
            if not single_output:
                print(result);
            else:
                results.append(result);

    if single_output:
        with open(output_file, "w", encoding="utf-8") as out_stream:
            if not args.fasta:
                out_stream.write(maf_header)  # Write header to single output file

            total_blocks = 0
            for block_list in results:
                if block_list:  # block_list is now a list of strings
                    for block in block_list:
                        out_stream.write(block)
                        total_blocks += 1

        print(f"Single output file written: {output_file} ({total_blocks} blocks)")

if __name__ == "__main__":
    main();
