#############################################################################
# Given a MAF file and index generated by maf_index.py, this script will
# fetch specific alignment blocks from the MAF file and print them to stdout.
#
# Gregg Thomas, April 2025
#############################################################################

import sys
import gzip
import random

#############################################################################

def detectCompression(filename):
# Detect compression of a file by examining the first lines in the file

    compression_type = "none";

    magic_dict = {
            b"\x1f\x8b\x08": "gz",
            # b"\x1f\x8b\x08\x08": "gz",
            b"\x42\x5a\x68": "bz2",
            b"\x50\x4b\x03\x04": "zip"
        }
    # An encoded set of possible "magic strings" that start different types of compressed files
    # From: https://www.garykessler.net/library/file_sigs.html
    # \x is the escape code for hex values
    # b converts strings to bytes

    max_len = max(len(x) for x in magic_dict)
    # The number of characters to read from the beginning of the file should be the length of
    # the longest magic string

    file_start = open(filename, "rb").read(max_len);
    # Read the beginning of the file up to the length of the longest magic string

    for magic_string in magic_dict:
        if file_start.startswith(magic_string):
            compression_type = magic_dict[magic_string];
    # Check each magic string against the start of the file

    return compression_type;

#############################################################################

def fetch_block(maf_fp, start, end):
    """
    Given an open file pointer (maf_fp) to the MAF file,
    seek to the 'start' byte position and read until 'end'.
    Returns the block as a decoded UTF-8 string.
    """
    maf_fp.seek(start)
    block_bytes = maf_fp.read(end - start)
    return block_bytes.decode("utf-8", errors="replace")

#############################################################################

def main():
    if len(sys.argv) < 3:
        sys.exit("Usage: python3 test_fetch_blocks_sample.py <maf_file> <index_file> [sample_count]")
    
    maf_file = sys.argv[1]
    index_file = sys.argv[2]

    maf_compression = detectCompression(maf_file);
# Check if the maf file is compressed

    if maf_compression == "gz":
        opener = gzip.open;
        # Open the input maf file as a binary file
    elif maf_compression == "none":
        opener = open;
        # Open the input maf file as a binary file
    else:
        raise ValueError(f"Unsupported compression type: {maf_compression}")

    # Default to sampling 5 blocks if sample_count is not provided
    sample_count = 5
    if len(sys.argv) >= 4:
        try:
            sample_count = int(sys.argv[3])
        except ValueError:
            sys.exit("Error: sample_count must be an integer.")

    # Read the index file and filter out comment/empty lines
    with open(index_file, "r") as idx_fp:
        index_lines = [line.strip() for line in idx_fp if line.strip() and not line.startswith("#")]

    # Adjust sample_count if it exceeds the number of available blocks
    if sample_count > len(index_lines):
        sample_count = len(index_lines)

    # Choose sample indices randomly and sort them (for easier debugging/output)
    #sample_indices = sorted(random.sample(range(len(index_lines)), sample_count))
    sample_indices = range(sample_count)
    print(f"Fetching {sample_count} blocks at indices: {sample_indices}")

    # Open the MAF file in binary mode so we can seek using byte offsets.
    with opener(maf_file, "rb") as maf_stream:
        for i in sample_indices:
            line = index_lines[i]
            fields = line.split("\t")
            try:
                # Extract the start and end byte positions (fields 6 and 7; 0-based index 5 and 6)
                start = int(fields[5])
                end = int(fields[6])
            except (IndexError, ValueError):
                print(f"Skipping malformed index line: {line}")
                continue

            # Fetch and display the block between the stored offsets
            block_text = fetch_block(maf_stream, start, end)
            print(f"=== Block {i} (bytes {start} to {end}) ===")
            print(block_text)
            print("-" * 80)

if __name__ == "__main__":
    main()